modLoader="kotlinforforge"
loaderVersion="${loaderVersionRange}"
license='${modLicense}'

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
authors="${modAuthors}"
description='''${modDescription}'''

[[dependencies.${modId}]]
modId="forge"
mandatory=true
versionRange="${forgeVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
mandatory=true
versionRange="${minecraftVersionRage}"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="create"
mandatory=true
versionRange="${createVersionRange}"
ordering="AFTER"
side="BOTH"

[[mixins]]
config = "${modId}.mixins.json"
